### ISSUE TITLE
Batch file - to - json conversion

### ISSUE THREAD

**Issue by vortexing** [getwilds/rcromwell#1]
Should add a function to convert a data frame full of manifest/batch information into a single, well formatted json for a workflow, so that it'd be easier for users to use a structured list of inputs to a workflow but then also make the workflow truly reproducible from a Cromwell perspective.  It currently will not re-load a batch file if it has the same name as the one before unless you turn off call caching.  Perhaps there's a way to turn off call caching for one task but until then, adjust.

**Comment by sckott** [comment]
@vortexing still think we should address this or no?

**Comment by vortexing** [comment]
I think this is a future feature or new tool - a tool that folks can use to take their excel spreadsheet in the lab or an R data frame and convert it into a custom `Array[struct]` and export a validate-able json.

**Comment by sckott** [comment]
okay, sounds good. and makes sense to leave here until figuring out whether and where to do this

**Comment by tefirman** [comment]
Don't think this would be used enough to be worth the effort for v1.X. Definitely open to reopening this after v2.0, but closing as "not planned" for now.
