### ISSUE TITLE
License for the package

### ISSUE THREAD

**Issue by sckott** [getwilds/rcromwell#14]
@vortexing the package currently has the GPL-3 license. During this refactor this is a good time to check over everything. Not saying we should do anything different, but is this the license you want for this package? Does it matter to you? Does the hutch care?

**Comment by vortexing** [comment]
No notes - totally up to you and @seankross about how DaSL wants to do it from here on out.

**Comment by sckott** [comment]
thanks, i'll talk to sean

**Comment by seankross** [comment]
MIT today, MIT tomorrow, MIT forever

**Comment by sckott** [comment]
😸 yes please

**Comment by vortexing** [comment]
Make it so!
