### ISSUE TITLE
prior art

### ISSUE THREAD

**Issue by sckott** [getwilds/rcromwell#30]
did stumble upon https://github.com/seandavi/wdlRunR though it's an archived package/project

**Comment by tefirman** [comment]
@sckott -- Not seeing where the prior art is in the linked repo, do you still see it in there?

**Comment by sckott** [comment]
That repo is the prior art 😄

**Comment by tefirman** [comment]
My late night brain thought you meant actual art of the prior FH logo from before the merger, not "prior art" in the patent context... 🤦‍♂️ 😆 100% my bad. Is this issue more of an FYI or do you think there's a potential task associated with it? e.g. identify how we can differentiate ourselves

**Comment by sckott** [comment]
Not anything to do - no. I just like to crawl github/internet when making a package to have a sense for what similar projects exist - and to list them in docs for posterity (if they're active, which this repo is not)
