### ISSUE TITLE
Failures doesn't appear to work anymore

### ISSUE THREAD

**Issue by sckott** [getwilds/rcromwell#35]
@vortexing Perhaps at one time failures worked but the function doesn't return anything anymore. 

Even using the [old version of the function before I arrived](https://github.com/getwilds/rcromwell/blob/e9a8787847bae1b2274ab2af17022fe57fa560d9/R/cromwellFailures.R)  doesn't change anything. 

The function pulls out `calls` https://github.com/getwilds/rcromwell/blob/main/R/cromwellFailures.R#L37 - but the data on failures appears to be in the slot `failures` instead. 

But because I still don't have a good array of examples it's possible I'm missing cases where failures are returned in the `calls` slot? 

Possibly this change from the changelog ? https://github.com/broadinstitute/cromwell/blob/develop/CHANGELOG.md#call-caching-failure-messages-5095 

If you look at the swagger docs for a running cromwell server there is a route `api/workflows/v1/{workflow_id}/metadata/failed-jobs`, but it's not in the Cromwell docs https://cromwell.readthedocs.io/en/stable/api/RESTAPI/  - and that route returns data in the swagger docs interactive thing, BUT NOT when you do the same http request ANYWHERE else. Super not frustrating :flip-table:

**Comment by vortexing** [comment]
Yes, it's entirely possible that cromwellFailures was developed before V45 Cromwell. However, I am 95% sure that the shiny app populates failed jobs.  ok I just tested it in the shiny app and it does return results!! You should fail more.  @sitapriyamoorthi and I have lots of failures to give you.

**Comment by sckott** [comment]
@sitapriyamoorthi can you provide some files that will fail that DO give you failure data in the shiny app?

**Comment by tefirman** [comment]
@sckott -- The failures metadata seems to come through fine for me in both the "Job Failures" table in the Shiny app and via `cromwell_failures` in rcromwell (see screenshots below). As an example, try submitting this modified version of the HelloDocker WDL: [helloDockerHostname.txt](https://github.com/user-attachments/files/16431692/helloDockerHostname.txt)

It just tries to remove a nonexistent file within its main task which will cause it to error out and fail.

![image](https://github.com/user-attachments/assets/e801829a-e7f6-4c7e-933c-b6ece86ee785)
![image](https://github.com/user-attachments/assets/75773e98-adbe-4a4d-be4b-e7783d885be6)

**Comment by sckott** [comment]
Thanks @tefirman 

That example works for me just as you laid out. nice. 

Okay, not sure what happened, but seems to be working, so i'll close this after removing some comments in the code as reminder about this
