### ISSUE TITLE
documentation tiny thing - self link

### ISSUE THREAD

**Issue by jayoung** [getwilds/rcromwell#41]
hi,

apologies if I start bombarding you with small things (a few months ago you asked for feedback) - you can tell me stop if it's annoying.

on this page: https://getwilds.org/rcromwell/

it's confusing that the link embedded here: 
```
Go to http://getwilds.org/rcromwell/ for rcromwell package documentation.
```
is pointing towards the same page we're already on.

would be great instead to link out to the "Get Started vignette" - https://getwilds.org/rcromwell/articles/rcromwell.html

or even better provide a bullet point list with links to the two docs I can see listed in the top header bar thing: Get Started, and Reference

thanks,

Janet

**Comment by tefirman** [comment]
@jayoung -- not annoying at all, thanks for taking a look! You're totally right, it's kind of self-defeating to point to the page you're already on, we should probably repurpose that text to describe what is contained in each section. Thanks for catching that!
