### ISSUE TITLE
Make cromwellJobs return timezone adjusted start and end times

### ISSUE THREAD

**Issue by vortexing** [getwilds/rcromwell#7]

**Comment by sckott** [comment]
@vortexing fixed this by removing some lines of code https://github.com/getwilds/rcromwell/commit/be738bd18964bacb3473f98213f9867de95af7d1  that were converting all columns to `character` after having done work to give columns particular class types. Perhaps the character coercion was for the shiny app?

**Comment by vortexing** [comment]
I would presume that I did the time zone adjustment during or not during DST and that's why it's off by an hour.  However, I would also presume that the coercion to character probably had a reason but I don't know what it was and I agree it's likely to show up sorted in the shiny app nicely which we can/should shift to the app not rcromwell.  Feels right to make this change here and then when we shift the shiny app from fh.wdlR to rcromwell, we'll have to troubleshoot a LOT o fthings including this.

**Comment by sckott** [comment]
> make this change here and then when we shift the shiny app from fh.wdlR to rcromwell, we'll have to troubleshoot a LOT o fthings including this

sounds good.
